name: Lasr-GPT35
class_name: LasrSearcher
api_type: "openai"
api_model: "gpt-3.5-turbo-0125"
api_url: "https://api.openai.com/v1"

num_iterations: 25
num_populations: 10
llm_weight: 0.001
early_stopping_condition: null
max_num_samples: 2000