name: Lasr-Llama31_8b
class_name: LasrSearcher
api_type: "vllm"
api_model: "meta-llama/Llama-3.1-8B-Instruct"
api_url: "http://localhost:{}/v1"

num_iterations: 25
num_populations: 10
llm_weight: 0.001
early_stopping_condition: null
max_num_samples: 2000