name: LlmDirect-Gpt4omini
class_name: LLMSRSearcher
api_type: "openai"
api_model: "gpt-4o-mini-2024-07-18"
api_url: "https://api.openai.com/v1/"
global_max_sample_num: 5
samples_per_prompt: 5
num_islands: 1
