name: Llmsr-GPT4omini
class_name: LLMSRSearcher
api_type: "openai"
api_model: "gpt-4o-mini-2024-07-18"
api_url: "https://api.openai.com/v1/"
global_max_sample_num: 1000
samples_per_prompt: 4
num_islands: 10